/* 
! API STUFF
test sheet: https://docs.google.com/spreadsheets/d/1LrllZ_5eB6z2OCEB2WaQXpGONdw9uY_lTOab74Gy-vY/edit#gid=0
api site: https://sheet.best/admin
api url = https://sheet.best/api/sheets/623f54ad-5a89-45cb-8b21-a088aac15e9f
doc = https://docs.sheet.best/#generating-your-rest-api
*/

export const Data = [
  {
    id: 1,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
  {
    id: 2,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Cmos Battery",
  },
  {
    id: 3,
    teclado: "sim",
    mouse: "não",
    monitor: "linhas no monitor",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 4,
    teclado: "sim",
    mouse: "sim",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Cmos Battery",
  },
  {
    id: 5,
    teclado: "sim",
    mouse: "sim",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 6,
    teclado: "sim",
    mouse: "sim",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 7,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 8,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Cmos Battery",
  },
  {
    id: 9,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 10,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
  {
    id: 11,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 12,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
  {
    id: 13,
    teclado: "sim",
    mouse: "sim",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 14,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 15,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
  {
    id: 16,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 17,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Cmos Battery",
  },
  {
    id: 18,
    teclado: "sim",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
  {
    id: 19,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Liga",
  },
  {
    id: 20,
    teclado: "não",
    mouse: "não",
    monitor: "sim",
    cabos: "Sem RJ45",
    gabinete: "Não Liga",
  },
];
